# Disable SELinux
- name: diskable SELinux
  selinux:
    state: disabled

#- name: Stop service firewalld, if started
#  ansible.builtin.service:
#    name: firewalld
#    state: stopped
#    enabled: no

- name: install Base package
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_packages }}"
    
