remove_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

docker_repo: https://download.docker.com/linux/centos/docker-ce.repo

docker_packges:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin