# Older versions of Docker were called docker or docker-engine. If these are installed, uninstall them, along with associated dependencies.
- name: remove Old docker package
  yum:
    name: "{{ item }}"
    state: removed
  loop: "{{ remove_packages }}"

# Install the yum-utils package (which provides the yum-config-manager utility) and set up the repository.

# install docker engine
- name: install yum-utils package 
  yum:
    name: yum-utils
    state: latest

#add docker repository
- name: add docker repository
  shell: yum-config-manager --add-repo "{{ docker_repo }}"

# install docker engine
- name: install Docker package
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_packges }}"