# Older versions of Docker were called docker or docker-engine. If these are installed, uninstall them, along with associated dependencies.
- name: remove Old docker package
  yum:
    name: "{{ item }}"
    state: removed
  loop: "{{ remove_packages }}"

# Install the yum-utils package (which provides the yum-config-manager utility) and set up the repository.

# install docker engine
- name: install yum-utils package 
  yum:
    name: yum-utils
    state: latest

#add docker repository
- name: add docker repository
  shell: yum-config-manager --add-repo "{{ docker_repo }}"

# install docker engine
- name: install Docker package
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_packges }}"

#start Dcoker Engine service
- name: Start Docker Engine
  service:
    name: docker
    state: started
    enabled: yes

# Check if the docker-compsoe is already installed
- name: Check that the docker-compose
  stat:
    path: {{ docker_compose_link_path }} 
  register: file_status


# docker-compose installtion
- name: Download docker-compose binary file
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_dest_path }}"
    mode: '07550'
  when: file_status.stat.exists == False

- name: Create short cut
  ansible.builtin.file:
    src: "{{ docker_compose_dest_path }}" 
    dest: "{{ docker_compose_link_path }}"
  when: file_status.stat.exists == False
  